name: popcor
channels:
    - defaults
    - conda-forge
    - anaconda
    - mosek

dependencies:
    - python=3.10
    - pip=22.3
    - flake8
    - pytest
    - black>=23.1

    - seaborn>=0.12.2
    - progressbar2>=4.2.0
    - jupyter>=1.0.0
    - mosek
    - pandas==1.5.3
    - spatialmath-python=1.1.11
    - suitesparse # used by sparseqr
    - pip:
      - -r doc/requirements.txt
      - -e .
