name: popr_small
channels:
    - defaults
    - conda-forge
    - anaconda
    - mosek

dependencies:
    - python=3.10
    - pip=22.3
    - numpy>=1.23.5
    - scipy>=1.15
    - cvxpy>=1.3.2
    - flake8
    - pytest
    - autograd
    - pip:
      - -r requirements.txt
